version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: eslint-config-airbnb
    versions:
    - 6.1.0
  - dependency-name: babel-eslint
    versions:
    - 9.0.0
